/* Add extra attribute mg_material */
 ALTER TABLE tdh_od.pipe_section ADD COLUMN mg_material  integer ;
COMMENT ON COLUMN tdh_od.pipe_section.mg_material IS 'Categories of materials Morges / Kategorien Material Morges / Categories des materiaux Morges';
ALTER TABLE tdh_od.pipe_section ADD COLUMN mg_diameter integer;
COMMENT ON COLUMN tdh_od.pipe_section.mg_diameter IS 'Linked to table of specified (nominal) diameters and material Morges for simplified recording / Verknüpft mit Tabelle der vorgegebenen (Nenn-)weiten und Material Morges zur vereinfachten Erfassung / Lier au tableau des diamètres (nominaux) prescrits et du matériau Morges pour simplifier la saisie';
 /*---------------------------------------------------------------------------------------*/
/* AJOUT DE LA TABLE DES MATERIAUX () */
/*---------------------------------------------------------------------------------------*/

CREATE TABLE tdh_vl.pipe_section_mg_material () INHERITS (tdh_vl.value_list_base);
ALTER TABLE tdh_vl.pipe_section_mg_material ADD CONSTRAINT pkey_tdh_vl_pipe_section_mg_material_code PRIMARY KEY (code);
 INSERT INTO tdh_vl.pipe_section_mg_material (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9513,9513,'plastic','Kunststoffmediumrohr','plastique', 'zzz_Kunststoffmediumrohr', 'rrr_Kunststoffmediumrohr', '', 'PMR', '', '', '', '', '', '', '', '', 'plastic', 'Kunststoffmediumrohr', 'Plastique', 'zzz_Kunststoffmediumrohr', 'rrr_Kunststoffmediumrohr', 'true');
 INSERT INTO tdh_vl.pipe_section_mg_material (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9514,9514,'plastic_duo','Kunststoffmediumrohr_Duo','plastique_duo', 'zzz_Kunststoffmediumrohr DUO', 'rrr_Kunststoffmediumrohr_DUO', '', '', '', '', '', '', '', '', '', '', 'plastic_duo', 'Kunststoffmediumrohr_Duo', 'Plastique DUO', 'zzz_Kunststoffmediumrohr DUO', 'rrr_Kunststoffmediumrohr DUO', 'true');
 INSERT INTO tdh_vl.pipe_section_mg_material (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9509,9509,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal', 'zzz_Kunststoffverbundmantelrohr', 'rrr_Kunststoffverbundmantelrohr', '', 'KMR', '', '', '', '', '', '', '', '', 'pre_insulated_metal', 'Kunststoffverbundmantelrohr', 'pré-isolés métal', 'zzz_Kunststoffverbundmantelrohr', 'rrr_Kunststoffverbundmantelrohr', 'true');
 INSERT INTO tdh_vl.pipe_section_mg_material (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9510,9510,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo', 'zzz_Kunststoffverbundmantelrohr DUO', 'rrr_Kunststoffverbundmantelrohr_DUO', '', '', '', '', '', '', '', '', '', '', 'pre_insulated_metal_duo', 'Kunststoffverbundmantelrohr_Duo', 'pré-isolés métal DUO', 'zzz_Kunststoffverbundmantelrohr DUO', 'rrr_Kunststoffverbundmantelrohr DUO', 'true');
 INSERT INTO tdh_vl.pipe_section_mg_material (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9511,9511,'flexible_metal','Metallmediumrohr','flexible_metal', 'zzz_Metallmediumrohr', 'rrr_Metallmediumrohr', '', 'MMR', '', '', '', '', '', '', '', '', 'flexible_metal', 'Metallmediumrohr', 'Flexible métal', 'zzz_Metallmediumrohr', 'rrr_Metallmediumrohr', 'true');
 INSERT INTO tdh_vl.pipe_section_mg_material (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9512,9512,'flexible_metal_duo','Metallmediumrohr_Duo','flexible_metal_duo', 'zzz_Metallmediumrohr DUO', 'rrr_Metallmediumrohr_DUO', '', '', '', '', '', '', '', '', '', '', 'flexible_metal_duo', 'Metallmediumrohr_Duo', 'Flexible métal DUO', 'zzz_Metallmediumrohr DUO', 'rrr_Metallmediumrohr DUO', 'true');
 INSERT INTO tdh_vl.pipe_section_mg_material (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9515,9515,'unknown','unbekannt','inconnu', 'zzz_unbekannt', '', '', 'NA', '', '', '', '', '', '', '', '', 'unknown', 'unbekannt', 'inconnu', '', '', 'true');
 ALTER TABLE tdh_od.pipe_section ADD CONSTRAINT fkey_vl_pipe_section_mg_material FOREIGN KEY (mg_material)
 REFERENCES tdh_vl.pipe_section_mg_material (code) MATCH SIMPLE
 ON UPDATE RESTRICT ON DELETE RESTRICT;



 /*---------------------------------------------------------------------------------------*/
/* AJOUT DE LA TABLE DES DIAMETRES NOMINAUX DE CONDUITES () */
/*---------------------------------------------------------------------------------------*/

CREATE TABLE tdh_vl.pipe_section_mg_diameter () INHERITS (tdh_vl.value_list_base);
/* ALTER TABLE tdh_vl.pipe_section_mg_material ADD COLUMN _displayname_fr character varying(30) COLLATE pg_catalog."default";
ALTER TABLE tdh_vl.pipe_section_mg_material ADD COLUMN _displayname_en character varying(30) COLLATE pg_catalog."default";
ALTER TABLE tdh_vl.pipe_section_mg_material ADD COLUMN _displayname_de character varying(30) COLLATE pg_catalog."default"; */
-- changed 13.2.25
--ALTER TABLE tdh_vl.pipe_section_mg_material ADD COLUMN diameter        character varying(30) COLLATE pg_catalog."default";
--ALTER TABLE tdh_vl.pipe_section_mg_material ADD COLUMN diameter_nominal  smallint;
ALTER TABLE tdh_vl.pipe_section_mg_diameter ADD COLUMN diameter          smallint;
ALTER TABLE tdh_vl.pipe_section_mg_diameter ADD COLUMN diameter_nominal character varying(30) COLLATE pg_catalog."default";
ALTER TABLE tdh_vl.pipe_section_mg_diameter ADD COLUMN diameter_inner numeric(7,3);
ALTER TABLE tdh_vl.pipe_section_mg_diameter ADD COLUMN diameter_outer numeric(7,3);
ALTER TABLE tdh_vl.pipe_section_mg_diameter ADD COLUMN fk_pipe_section_mg_material integer;
ALTER TABLE tdh_vl.pipe_section_mg_diameter ADD CONSTRAINT vl_pipe_section_mg_material_pk PRIMARY KEY (code);

COMMENT ON TABLE tdh_vl.pipe_section_mg_diameter
    IS 'List of materials for pipe. All the possible combinations material/diameter are listed in this table. _displayname_fr, _displayname_de and _displayname_en are automatically generated by rules on insert and update. They are meant to be used in QGIS for the combo box of pipe.fk_material.

Remark: The pipe industry maintains two different ways to refer to the dimension of a pipe:
- Nominal Diameter (DN) which is commonly used for steel/iron, plastic pipes. Both diameter_inner and diameter_outer refer to the tube.
- Outer Diameter(OD) is taken into consideration for the insulation of the pre-insulated metal, flexible metal and plastic pipes (from 1 to 3 are maintained in pipe_section_pipe_od table)

The DN is a number that represents the approximate interior diameter, in mm. The value represents only an approximation of the pipe diameter so that engineers use a nice round number; the actual value is usually off by a few mm.
So, when referring simply to the diameter, it is assumed that for plastic pipes you''re referring to the outer one, and for iron/steel and GRP ones to the approximate interior one - Nominal Diameter (DN).
';

COMMENT ON COLUMN tdh_vl.pipe_section_mg_diameter.diameter
    IS 'Represents the usual name of the pipe diameter (how you call it).
Commonly, it should be equivalent to:
- the external diameter for plastic pipe
- the nominal diameter for iron/steel and GRP';

COMMENT ON COLUMN tdh_vl.pipe_section_mg_diameter.diameter_nominal
    IS 'The nominal diameter (DN) is a number that represents the approximate interior diameter, in mm.
It''s commonly used when referring steel/iron pipes but also for GRP.
It matches the official attribute pipe_section.diameter_nominal';


COMMENT ON COLUMN tdh_vl.pipe_section_mg_diameter.diameter_inner
    IS 'It matches the official attribute pipe_section.diameter_outer';

COMMENT ON COLUMN tdh_vl.pipe_section_mg_diameter.diameter_outer
    IS 'Commonly used when referring to plastic pipes.
It matches the official attribute pipe_section.diameter_outer';

ALTER TABLE tdh_od.pipe_section ADD CONSTRAINT fkey_vl_pipe_section_mg_diameter FOREIGN KEY (mg_diameter)
 REFERENCES tdh_vl.pipe_section_mg_diameter (code) MATCH SIMPLE
 ON UPDATE RESTRICT ON DELETE RESTRICT;

 /*---------------------------------------------------------------------------------------*/
/* AJOUT DE LISTE DE VALEURS DES DIAMETRES NOMINAUX DE CONDUITES () */
/*---------------------------------------------------------------------------------------*/

-- pre_insulated_metal
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8080,8080,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 20','KMR 20', 'AC 20',NULL,NULL,'20',20,'21.600','26.900',9509,True);
-- diameter text statt zahl, diameter_inner / outer in mm?

INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8081,8081,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 25','KMR 25', 'AC 25',NULL,NULL,'25',25,'28.500','33.700',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8082,8082,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 32','KMR 32', 'AC 32',NULL,NULL,'32',32,'37.200','42.400',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8083,8083,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 40','KMR 40', 'AC 40',NULL,NULL,'40',40,'43.100','48.300',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8084,8084,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 50','KMR 50', 'AC 50',NULL,NULL,'50',50,'54.500','60.300',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8085,8085,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 65','KMR 65', 'AC 65',NULL,NULL,'65',65,'70.300','76.100',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8086,8086,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 80','KMR 80', 'AC 80',NULL,NULL,'80',80,'82.500','88.900',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8087,8087,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 100','KMR 100', 'AC 100',NULL,NULL,'10',100,'107.100','114.300',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8088,8088,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 125','KMR 125', 'AC 125',NULL,NULL,'125',125,'132.500','139.700',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8089,8089,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 150','KMR 150', 'AC 150',NULL,NULL,'150',150,'160.300','168.300',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8090,8090,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 200','KMR 200', 'AC 200',NULL,NULL,'200',200,'210.100','219.100',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8091,8091,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 250','KMR 250', 'AC 250',NULL,NULL,'250',250,'263.000','273.000',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8092,8092,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 300','KMR 300', 'AC 300',NULL,NULL,'300',300,'312.700','323.900',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8093,8093,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 350','KMR 350', 'AC 350',NULL,NULL,'250',350,'344.400','355.600',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8094,8094,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 400','KMR 400', 'AC 400',NULL,NULL,'400',400,'393.800','406.400',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8095,8095,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 450','KMR 450', 'AC 450',NULL,NULL,'450',450,'444.600','457.200',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8096,8096,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 500','KMR 500', 'AC 500',NULL,NULL,'500',500,'495.400','508.000',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8097,8097,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 600','KMR 600', 'AC 600',NULL,NULL,'600',600,'595.800','610.000',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8098,8098,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 700','KMR 700', 'AC 700',NULL,NULL,'700',700,'695.000','711.000',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8099,8099,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 800','KMR 800', 'AC 800',NULL,NULL,'800',800,'795.400','813.000',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8100,8100,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 900','KMR 900', 'AC 900',NULL,NULL,'900',900,'894.000','914.000',9509,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8101,8101,'pre_insulated_metal','Kunststoffverbundmantelrohr','pre_isoles_metal',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal','Kunststoffverbundmantelrohr','pré-isolés métal',NULL,NULL,'ST 100','KMR 1000', 'AC 1000',NULL,NULL,'1000',1000,'994.000','1016.000',9509,True);

-- pre_insulated_metal_duo
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8102,8102,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal duo','Kunststoffverbundmantelrohr DUO','pré-isolés métal DUO',NULL,NULL,'ST 20','KMR 20', 'AC 20',NULL,NULL,'20',20,'21.700','26.900',9510,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8103,8103,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal duo','Kunststoffverbundmantelrohr DUO','pré-isolés métal DUO',NULL,NULL,'ST 25','KMR 25', 'AC 25',NULL,NULL,'25',25,'28.500','33.700',9510,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8104,8104,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal duo','Kunststoffverbundmantelrohr DUO','pré-isolés métal DUO',NULL,NULL,'ST 32','KMR 32', 'AC 32',NULL,NULL,'32',32,'37.200','42.400',9510,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8105,8105,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal duo','Kunststoffverbundmantelrohr DUO','pré-isolés métal DUO',NULL,NULL,'ST 40','KMR 40','AC 40',NULL,NULL,'40',40,'43.100','48.300',9510,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8106,8106,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal duo','Kunststoffverbundmantelrohr DUO','pré-isolés métal DUO',NULL,NULL,'ST 50','KMR 50','AC 50',NULL,NULL,'50',50,'54.500','60.300',9510,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8107,8107,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo',NULL,NULL,'ST','KMR','AC',NULL,NULL
,'Pre-insulated metal duo','Kunststoffverbundmantelrohr DUO','pré-isolés métal DUO',NULL,NULL,'ST 65','KMR 65','AC 65',NULL,NULL,'65',65,'70.300','76.100',9510,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8108,8108,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal duo','Kunststoffverbundmantelrohr DUO','pré-isolés métal DUO',NULL,NULL,'ST 80','KMR 80','AC 80',NULL,NULL,'80',80,'82.500','88.900',9510,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8109,8109,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal duo','Kunststoffverbundmantelrohr DUO','pré-isolés métal DUO',NULL,NULL,'ST 100','KMR 100','AC 100',NULL,NULL,'100',100,'107.100','114.300',9510,True);

INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8110,8110,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal duo','Kunststoffverbundmantelrohr DUO','pré-isolés métal DUO',NULL,NULL,'ST 125','KMR 125','AC 125',NULL,NULL,'125',125,'132.500','139.700',9510,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8111,8111,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal duo','Kunststoffverbundmantelrohr DUO','pré-isolés métal DUO',NULL,NULL,'ST 150','KMR 150','AC 150',NULL,NULL,'150',150,'160.300','168.300',9510,True);

INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8112,8112,'pre_insulated_metal_duo','Kunststoffverbundmantelrohr_Duo','pre_isoles_metal_duo',NULL,NULL,'ST','KMR','AC',NULL,NULL,'Pre-insulated metal duo','Kunststoffverbundmantelrohr DUO','pré-isolés métal DUO',NULL,NULL,'ST 200','KMR 200','AC 200',NULL,NULL,'200',200,'210.100','219.100',9510,True);

-- flexible metal 9511,True
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8113,8113,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 20','MMR 20','AC 20',NULL,NULL,'20',20,'22.000','25.500',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8114,8114,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 25','MMR 25','AC 25',NULL,NULL,'25',25,'30.000','34.000',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8115,8115,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 32','MMR 32','AC 32',NULL,NULL,'32',32,'38.900','43.800',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8116,8116,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 40','MMR 40','AC 40',NULL,NULL,'40',40,'48.500','54.500',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8117,8117,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 50','MMR 50','AC 50',NULL,NULL,'50',50,'60.000','66.500',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8118,8118,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 65','MMR 65','AC 65',NULL,NULL,'65',65,'75.800','85.600',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8119,8119,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 80','MMR 80','AC 80',NULL,NULL,'80',80,'98.000','109.200',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8120,8120,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 100','MMR 100','AC 100',NULL,NULL,'100',100,'127.000','142.900',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8121,8121,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 125','MMR 125','AC 125',NULL,NULL,'125',125,'147.000','162.700',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8122,8122,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 150','MMR 150','AC 150',NULL,NULL,'150',150,'197.500','218.000',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8123,8123,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 200','MMR 200','AC 200',NULL,NULL,'200',200,'210.100','219.100',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8124,8124,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 250','MMR 250','AC 250',NULL,NULL,'250',250,'263.000','273.000',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8125,8125,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 300','MMR 300','AC 300',NULL,NULL,'300',300,'312.700','323.900',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8126,8126,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 350','MMR 350','AC 350',NULL,NULL,'350',350,'344.400','355.600',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8127,8127,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 400','MMR 400','AC 400',NULL,NULL,'400',400,'393.800','406.400',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8128,8128,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 450','MMR 450','AC 450',NULL,NULL,'450',450,'444.600','457.200',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8129,8129,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 500','MMR 500','AC 500',NULL,NULL,'500',500,'495.400','508.000',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8130,8130,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 600','MMR 600','AC 600',NULL,NULL,'600',600,'595.800','610.000',9511,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8131,8131,'flexible_metal','Metallmediumrohr','flexible_metal',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal','Metallmediumrohr','Flexible métal',NULL,NULL,'ST 700','MMR 700','AC 700',NULL,NULL,'700',700,'695.000','711.000',9511,True);

-- flexible material duo ,9512,True
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8132,8132,'flexible_metal_duo','Metallmediumrohr_Duo','flexible_metal_duo',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal_duo','Metallmediumrohr DUO','Flexible métal DUO',NULL,NULL,'ST 20','MMR 20','AC 20',NULL,NULL,'20',20,'22.000','25.500',9512,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8133,8133,'flexible_metal_duo','Metallmediumrohr_Duo','flexible_metal_duo',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal_duo','Metallmediumrohr DUO','Flexible métal DUO',NULL,NULL,'ST 25','MMR 25','AC 25',NULL,NULL,'25',25,'30.000','34.000',9512,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8134,8134,'flexible_metal_duo','Metallmediumrohr_Duo','flexible_metal_duo',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal_duo','Metallmediumrohr DUO','Flexible métal DUO',NULL,NULL,'ST 32','MMR 32','AC 32',NULL,NULL,'32',32,'38.900','43.800',9512,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8135,8135,'flexible_metal_duo','Metallmediumrohr_Duo','flexible_metal_duo',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal_duo','Metallmediumrohr DUO','Flexible métal DUO',NULL,NULL,'ST 40','MMR 40','AC 40',NULL,NULL,'40',40,'48.500','54.500',9512,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8136,8136,'flexible_metal_duo','Metallmediumrohr_Duo','flexible_metal_duo',NULL,NULL,'ST','MMR','AC',NULL,NULL,'flexible_metal_duo','Metallmediumrohr DUO','Flexible métal DUO',NULL,NULL,'ST 50','MMR 50','AC 50',NULL,NULL,'50',50,'60.000','66.500',9512,True);

-- plastic ,9513,True
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8137,8137,'plastic','Kunststoffmediumrohr','plastique',NULL,NULL,'PE','PMR','PE',NULL,NULL,'Plastic','Kunststoffmediumrohr','Plastique',NULL,NULL,'PE 20','PMR 20','PE 20',NULL,NULL,'20',20,'20.400','25.000',9513,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8138,8138,'plastic','Kunststoffmediumrohr','plastique',NULL,NULL,'PE','PMR','PE',NULL,NULL,'Plastic','Kunststoffmediumrohr','Plastique',NULL,NULL,'PE 25','PMR 25','PE 25',NULL,NULL,'25',25,'26.200','32.000',9513,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8139,8139,'plastic','Kunststoffmediumrohr','plastique',NULL,NULL,'PE','PMR','PE',NULL,NULL,'Plastic','Kunststoffmediumrohr','Plastique',NULL,NULL,'PE 32','PMR 32','PE 32',NULL,NULL,'32',32,'32.600','40.000',9513,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8140,8140,'plastic','Kunststoffmediumrohr','plastique',NULL,NULL,'PE','PMR','PE',NULL,NULL,'Plastic','Kunststoffmediumrohr','Plastique',NULL,NULL,'PE 40','PMR 40','PE 40',NULL,NULL,'40',40,'40.800','50.000',9513,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8141,8141,'plastic','Kunststoffmediumrohr','plastique',NULL,NULL,'PE','PMR','PE',NULL,NULL,'Plastic','Kunststoffmediumrohr','Plastique',NULL,NULL,'PE 50','PMR 50','PE 50',NULL,NULL,'50',50,'51.400','63.000',9513,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8142,8142,'plastic','Kunststoffmediumrohr','plastique',NULL,NULL,'PE','PMR','PE',NULL,NULL,'Plastic','Kunststoffmediumrohr','Plastique',NULL,NULL,'PE 65','PMR 65','PE 65',NULL,NULL,'65',65,'61.400','75.000',9513,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8143,8143,'plastic','Kunststoffmediumrohr','plastique',NULL,NULL,'PE','PMR','PE',NULL,NULL,'Plastic','Kunststoffmediumrohr','Plastique',NULL,NULL,'PE 80','PMR 80','PE 80',NULL,NULL,'80',80,'73.600','90.000',9513,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8144,8144,'plastic','Kunststoffmediumrohr','plastique',NULL,NULL,'PE','PMR','PE',NULL,NULL,'Plastic','Kunststoffmediumrohr','Plastique',NULL,NULL,'PE 100','PMR 100','PE 100',NULL,NULL,'100',100,'90.000','110.000',9513,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8145,8145,'plastic','Kunststoffmediumrohr','plastique',NULL,NULL,'PE','PMR','PE',NULL,NULL,'Plastic','Kunststoffmediumrohr','Plastique',NULL,NULL,'PE 125','PMR 125','PE 125',NULL,NULL,'125',125,'102.200','125.000',9513,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8146,8146,'plastic','Kunststoffmediumrohr','plastique',NULL,NULL,'PE','PMR','PE',NULL,NULL,'Plastic','Kunststoffmediumrohr','Plastique',NULL,NULL,'PE 150','PMR 150','PE 150',NULL,NULL,'150',150,'130.800','160.000',9513,True);


-- plastic duo ,9514,True
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8147,8147,'plastic_duo','Kunststoffmediumrohr_Duo','plastique_duo',NULL,NULL,'PE','PMR','PE',NULL,NULL,'plastic_duo','Kunststoffmediumrohr Duo','Plastique DUO',NULL,NULL,'PE 20','PMR 20','PE 20',NULL,NULL,'20',20,'20.400','25.000',9514,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8148,8148,'plastic_duo','Kunststoffmediumrohr_Duo','plastique_duo',NULL,NULL,'PE','PMR','PE',NULL,NULL,'plastic_duo','Kunststoffmediumrohr Duo','Plastique DUO',NULL,NULL,'PE 25','PMR 25','PE 25',NULL,NULL,'25',25,'26.200','32.000',9514,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8149,8149,'plastic_duo','Kunststoffmediumrohr_Duo','plastique_duo',NULL,NULL,'PE','PMR','PE',NULL,NULL,'plastic_duo','Kunststoffmediumrohr Duo','Plastique DUO',NULL,NULL,'PE 32','PMR 32','PE 32',NULL,NULL,'32',32,'32.600','40.000',9514,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8150,8150,'plastic_duo','Kunststoffmediumrohr_Duo','plastique_duo',NULL,NULL,'PE','PMR','PE',NULL,NULL,'plastic_duo','Kunststoffmediumrohr Duo','Plastique DUO',NULL,NULL,'PE 40','PMR 40','PE 40',NULL,NULL,'40',40,'40.800','50.000',9514,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8151,8151,'plastic_duo','Kunststoffmediumrohr_Duo','plastique_duo',NULL,NULL,'PE','PMR','PE',NULL,NULL,'plastic_duo','Kunststoffmediumrohr Duo','Plastique DUO',NULL,NULL,'PE 50','PMR 50','PE 50',NULL,NULL,'50',50,'51.400','63.000',9514,True);

-- unbekannt
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8280,8280,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 20','UNB 20','INC 20',NULL,NULL,'20',20,'21.600','26.900',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8281,8281,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 25','UNB 25','INC 25',NULL,NULL,'25',25,'28.500','33.700',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8282,8282,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 32','UNB 32','INC 32',NULL,NULL,'32',32,'37.200','42.400',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8283,8283,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 40','UNB 40','INC 40',NULL,NULL,'40',40,'43.100','48.300',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8284,8284,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 50','UNB 50','INC 50',NULL,NULL,'50',50,'54.500','60.300',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8285,8285,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 65','UNB 65','INC 65',NULL,NULL,'65',65,'70.300','76.100',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8286,8286,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 80','UNB 80','INC 80',NULL,NULL,'80',80,'82.500','88.900',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8287,8287,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 100','UNB 100','INC 100',NULL,NULL,'100',100,'107.100','114.300',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8288,8288,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 125','UNB 125','INC 125',NULL,NULL,'125',125,'132.500','139.700',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8289,8289,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 150','UNB 150','INC 150',NULL,NULL,'150',150,'160.300','168.300',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8290,8290,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 200','UNB 200','INC 200',NULL,NULL,'200',200,'210.100','219.100',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8291,8291,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 250','UNB 250','INC 250',NULL,NULL,'250',250,'263.000','273.000',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8292,8292,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 300','UNB 300','INC 300',NULL,NULL,'300',300,'312.700','323.900',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8293,8293,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 350','UNB 350','INC 350',NULL,NULL,'350',350,'344.400','355.600',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8294,8294,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 400','UNB 400','INC 400',NULL,NULL,'400',400,'393.800','406.400',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8295,8295,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 450','UNB 450','INC 450',NULL,NULL,'450',450,'444.600','457.200',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8296,8296,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 500','UNB 500','INC 500',NULL,NULL,'500',500,'495.400','508.000',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8297,8297,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 600','UNB 600','INC 600',NULL,NULL,'600',600,'595.800','610.000',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8298,8298,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 700','UNB 700','INC 700',NULL,NULL,'700',700,'695.000','711.000',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8299,8299,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 800','UNB 800','INC 800',NULL,NULL,'800',800,'795.400','813.000',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8300,8300,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 900','UNB 900','INC 900',NULL,NULL,'900',900,'894.000','914.000',9515,True);
INSERT INTO tdh_vl.pipe_section_mg_diameter (code,vsacode,value_en,value_de,value_fr,value_it,value_ro,abbr_en,abbr_de,abbr_fr,abbr_it,abbr_ro,description_en, description_de, description_fr, description_it, description_ro, display_en, display_de,display_fr,display_it,display_ro,diameter,diameter_nominal,diameter_inner,diameter_outer,fk_pipe_section_mg_material,active) VALUES (8301,8301,'unknown','unbekannt','inconnu',NULL,NULL,'UNK','UNB','INC',NULL,NULL,'unknown','unbekannt','inconnu',NULL,NULL,'UNK 1000','UNB 1000','INC 1000',NULL,NULL,'1000',1000,'994.000','1016.000',9515,True);
