------------------------------------------
/* GRANT on schemas - once per database */
------------------------------------------

/* Viewer */
GRANT USAGE ON SCHEMA tdh_od  TO tdh_viewer;
GRANT USAGE ON SCHEMA tdh_sys TO tdh_viewer;
GRANT USAGE ON SCHEMA tdh_vl  TO tdh_viewer;
GRANT USAGE ON SCHEMA tdh_cfg  TO tdh_viewer;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA tdh_od  TO tdh_viewer;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA tdh_sys TO tdh_viewer;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA tdh_vl  TO tdh_viewer;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA tdh_cfg  TO tdh_viewer;

GRANT SELECT, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA tdh_od  TO tdh_viewer;
GRANT SELECT, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA tdh_sys TO tdh_viewer;
GRANT SELECT, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA tdh_vl  TO tdh_viewer;
GRANT SELECT, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA tdh_cfg  TO tdh_viewer;

ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_od  GRANT SELECT, REFERENCES, TRIGGER ON TABLES TO tdh_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_sys GRANT SELECT, REFERENCES, TRIGGER ON TABLES TO tdh_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_vl  GRANT SELECT, REFERENCES, TRIGGER ON TABLES TO tdh_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_cfg  GRANT SELECT, REFERENCES, TRIGGER ON TABLES TO tdh_viewer;


/* User */
GRANT ALL ON SCHEMA tdh_od TO tdh_user;
GRANT ALL ON ALL TABLES IN SCHEMA tdh_od TO tdh_user;
GRANT ALL ON ALL SEQUENCES IN SCHEMA tdh_od TO tdh_user;
GRANT ALL ON ALL TABLES IN SCHEMA tdh_cfg TO tdh_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_od GRANT ALL ON TABLES TO tdh_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_od GRANT ALL ON SEQUENCES TO tdh_user;

DO $$ BEGIN EXECUTE 'GRANT CREATE ON DATABASE ' || (SELECT current_database()) || ' TO "tdh_user"'; END $$;  -- required for ili2pg imports/exports

/* Manager */
GRANT ALL ON SCHEMA tdh_vl TO tdh_manager;
GRANT ALL ON ALL TABLES IN SCHEMA tdh_vl TO tdh_manager;
GRANT ALL ON ALL SEQUENCES IN SCHEMA tdh_vl TO tdh_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_vl GRANT ALL ON TABLES TO tdh_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_vl GRANT ALL ON SEQUENCES TO tdh_manager;

/* SysAdmin */
GRANT ALL ON SCHEMA tdh_sys TO tdh_sysadmin;
GRANT ALL ON ALL TABLES IN SCHEMA tdh_sys TO tdh_sysadmin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA tdh_sys TO tdh_sysadmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_sys GRANT ALL ON TABLES TO tdh_sysadmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_sys GRANT ALL ON SEQUENCES TO tdh_sysadmin;

/*
-- Revoke

REVOKE ALL ON SCHEMA tdh_od  FROM tdh_viewer;
REVOKE ALL ON SCHEMA tdh_sys FROM tdh_viewer;
REVOKE ALL ON SCHEMA tdh_vl  FROM tdh_viewer;

REVOKE ALL ON ALL TABLES IN SCHEMA tdh_od  FROM tdh_viewer;
REVOKE ALL ON ALL TABLES IN SCHEMA tdh_sys FROM tdh_viewer;
REVOKE ALL ON ALL TABLES IN SCHEMA tdh_vl  FROM tdh_viewer;

ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_od  REVOKE ALL ON TABLES  FROM tdh_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_sys REVOKE ALL ON TABLES  FROM tdh_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA tdh_vl  REVOKE ALL ON TABLES  FROM tdh_viewer;

*/
