BEGIN;

------- This has to come after organisation creation otherwise constraints will fail.
------- Datamedia table using same structure as VSA KEK
-------
CREATE TABLE tdh_od.data_media
(
   obj_id varchar(16) NOT NULL,
   CONSTRAINT pkey_tdh_od_data_media_obj_id PRIMARY KEY (obj_id)
)
WITH (
   OIDS = False
);
CREATE SEQUENCE tdh_od.seq_data_media_oid INCREMENT 1 MINVALUE 0 MAXVALUE 999999 START 0;
COMMENT ON COLUMN tdh_od.data_media.obj_id IS 'INTERLIS STANDARD OID (with Postfix/Präfix), see www.interlis.ch';
 ALTER TABLE tdh_od.data_media ADD COLUMN identifier text;
 ALTER TABLE tdh_od.data_media ADD CONSTRAINT vo_identifier_length_max_60 CHECK(char_length(identifier)<=60);
COMMENT ON COLUMN tdh_od.data_media.identifier IS 'yyy_Name des Datenträgers. Bei elektronischen Datenträgern normalerweise das Volume-Label. Bei einem Server der Servername. Bei analogen Videobändern die Bandnummer. / Name des Datenträgers. Bei elektronischen Datenträgern normalerweise das Volume-Label. Bei einem Server der Servername. Bei analogen Videobändern die Bandnummer. / Nom du support de données. Pour les supports de données électroniques, normalement le label volume. Pour un serveur, le nom du serveur. Pour des bandes vidéo analogiques, les numéros de bandes.';
 ALTER TABLE tdh_od.data_media ADD COLUMN kind  integer ;
COMMENT ON COLUMN tdh_od.data_media.kind IS 'Describes the type of data media / Beschreibt die Art des Datenträgers / Décrit le genre de support de données';
 ALTER TABLE tdh_od.data_media ADD COLUMN location text;
 ALTER TABLE tdh_od.data_media ADD CONSTRAINT vo_location_length_max_50 CHECK(char_length(location)<=50);
COMMENT ON COLUMN tdh_od.data_media.location IS 'Location of the data medium / Ort, wo sich der Datenträger befindet / Emplacement du support de données';
 ALTER TABLE tdh_od.data_media ADD COLUMN path text;
 ALTER TABLE tdh_od.data_media ADD CONSTRAINT vo_path_length_max_1023 CHECK(char_length(path)<=1023);
COMMENT ON COLUMN tdh_od.data_media.path IS 'Access path to the data carrier. e.g. DVD drive -> D: , server -> //server/videos, hard disk -> c:/videos . For web servers -> URI (URL). Empty for an analog video tape / Zugriffspfad zum Datenträger. z.B. DVD-Laufwerk -> D: , Server -> //server/videos, Harddisk -> c:/videos . Bei Webserver eine URI (URL). Bei einem analogen Videoband leer / Chemin d’accès au support de données, p. ex. lecteur DVD -> D: , - serveur -> //server/videos , disque dur -> c:/videos , serveur_web -> URI(URL). Pour une bande vidéo analogique: vide';
 ALTER TABLE tdh_od.data_media ADD COLUMN remark text;
 ALTER TABLE tdh_od.data_media ADD CONSTRAINT vo_remark_length_max_80 CHECK(char_length(remark)<=80);
COMMENT ON COLUMN tdh_od.data_media.remark IS 'General remarks / Bemerkungen zum Datenträger / Remarques concernant le support de données';
 ALTER TABLE tdh_od.data_media ADD COLUMN last_modification TIMESTAMP without time zone DEFAULT now();
COMMENT ON COLUMN tdh_od.data_media.last_modification IS 'Last modification / Letzte_Aenderung / Derniere_modification: INTERLIS_1_DATE';
 ALTER TABLE tdh_od.data_media ADD COLUMN fk_dataowner varchar(16);
COMMENT ON COLUMN tdh_od.data_media.fk_dataowner IS 'Foreignkey to Metaattribute dataowner (as an organisation) - this is the person or body who is allowed to delete, change or maintain this object / Metaattribut Datenherr ist diejenige Person oder Stelle, die berechtigt ist, diesen Datensatz zu löschen, zu ändern bzw. zu verwalten / Maître des données gestionnaire de données, qui est la personne ou l''organisation autorisée pour gérer, modifier ou supprimer les données de cette table/classe';
 ALTER TABLE tdh_od.data_media ADD COLUMN fk_provider varchar(16);
COMMENT ON COLUMN tdh_od.data_media.fk_provider IS 'Foreignkey to Metaattribute provider (as an organisation) - this is the person or body who delivered the data / Metaattribut Datenlieferant ist diejenige Person oder Stelle, die die Daten geliefert hat / FOURNISSEUR DES DONNEES Organisation qui crée l’enregistrement de ces données ';

-------File table using same structure as VSA KEK
-------
CREATE TABLE tdh_od.file
(
   obj_id varchar(16) NOT NULL,
   CONSTRAINT pkey_tdh_od_file_obj_id PRIMARY KEY (obj_id)
)
WITH (
   OIDS = False
);
CREATE SEQUENCE tdh_od.seq_file_oid INCREMENT 1 MINVALUE 0 MAXVALUE 999999 START 0;
COMMENT ON COLUMN tdh_od.file.obj_id IS 'INTERLIS STANDARD OID (with Postfix/Präfix), see www.interlis.ch';
 ALTER TABLE tdh_od.file ADD COLUMN classname  integer ;
COMMENT ON COLUMN tdh_od.file.classname IS 'Specifies the classname of the VSA-DSS data model to which the file belongs. In principle, all classes are possible. In the context of sewer television recordings, mainly channel, manhole damage, channel damage and examination. / Gibt an, zu welcher Klasse des VSA-DSS-Datenmodells die Datei gehört. Grundsätzlich alle Klassen möglich. Im Rahmen der Kanalfernsehaufnahmen hauptsächlich Kanal, Normschachtschaden, Kanalschaden und Untersuchung. / Indique à quelle classe du modèle de données de VSA-SDEE appartient le fichier. Toutes les classes sont possible. Surtout CANALISATION, DOMMAGE_CHAMBRE_STANDARD, DOMMAGE_CANALISATION, EXAMEN.';
 ALTER TABLE tdh_od.file ADD COLUMN identifier text;
 ALTER TABLE tdh_od.file ADD CONSTRAINT fi_identifier_length_max_120 CHECK(char_length(identifier)<=120);
COMMENT ON COLUMN tdh_od.file.identifier IS 'yyy_Name der Datei mit Dateiendung. Z.B video_01.mpg oder haltung_01.ipf / Name der Datei mit Dateiendung. Z.B video_01.mpg oder haltung_01.ipf / Nom du fichier avec terminaison du fichier. P. ex. video_01.mpg ou canalisation_01.ipf';
 ALTER TABLE tdh_od.file ADD COLUMN kind  integer ;
COMMENT ON COLUMN tdh_od.file.kind IS 'yyy_Beschreibt die Art der Datei. Für analoge Videos auf Bändern ist der Typ "Video" einzusetzen. Die Bezeichnung wird dann gleich gesetzt wie die Bezeichnung des Videobandes. / Beschreibt die Art der Datei. Für analoge Videos auf Bändern ist der Typ "Video" einzusetzen. Die Bezeichnung wird dann gleich gesetzt wie die Bezeichnung des Videobandes. / Décrit le type de fichier. Pour les vidéos analo-giques sur bandes, le type « vidéo » doit être entré. La désignation sera ensuite la même que celle de la bande vidéo.';
 ALTER TABLE tdh_od.file ADD COLUMN object text;
 ALTER TABLE tdh_od.file ADD CONSTRAINT fi_object_length_max_16 CHECK(char_length(object)<=16);
COMMENT ON COLUMN tdh_od.file.object IS 'yyy_Objekt-ID (OID) des Datensatzes zu dem die Datei gehört / Objekt-ID (OID) des Datensatzes zu dem die Datei gehört / Identification de l’ensemble de données auquel le fichier appartient (OID)';
 ALTER TABLE tdh_od.file ADD COLUMN path_relative text;
 ALTER TABLE tdh_od.file ADD CONSTRAINT fi_path_relative_length_max_200 CHECK(char_length(path_relative)<=200);
COMMENT ON COLUMN tdh_od.file.path_relative IS 'yyy_Zusätzlicher Relativer Pfad, wo die Datei auf dem Datenträger zu finden ist. Z.B. DVD_01. / Zusätzlicher Relativer Pfad, wo die Datei auf dem Datenträger zu finden ist. Z.B. DVD_01. / Accès relatif supplémentaire à l’emplacement du fichier sur le support de données. P. ex. DVD_01';
 ALTER TABLE tdh_od.file ADD COLUMN remark text;
 ALTER TABLE tdh_od.file ADD CONSTRAINT fi_remark_length_max_80 CHECK(char_length(remark)<=80);
COMMENT ON COLUMN tdh_od.file.remark IS 'General remarks / Allgemeine Bemerkungen / Remarques générales';
 ALTER TABLE tdh_od.file ADD COLUMN last_modification TIMESTAMP without time zone DEFAULT now();
COMMENT ON COLUMN tdh_od.file.last_modification IS 'Last modification / Letzte_Aenderung / Derniere_modification: INTERLIS_1_DATE';
 ALTER TABLE tdh_od.file ADD COLUMN fk_dataowner varchar(16);
COMMENT ON COLUMN tdh_od.file.fk_dataowner IS 'Foreignkey to Metaattribute dataowner (as an organisation) - this is the person or body who is allowed to delete, change or maintain this object / Metaattribut Datenherr ist diejenige Person oder Stelle, die berechtigt ist, diesen Datensatz zu löschen, zu ändern bzw. zu verwalten / Maître des données gestionnaire de données, qui est la personne ou l''organisation autorisée pour gérer, modifier ou supprimer les données de cette table/classe';
 ALTER TABLE tdh_od.file ADD COLUMN fk_provider varchar(16);
COMMENT ON COLUMN tdh_od.file.fk_provider IS 'Foreignkey to Metaattribute provider (as an organisation) - this is the person or body who delivered the data / Metaattribut Datenlieferant ist diejenige Person oder Stelle, die die Daten geliefert hat / FOURNISSEUR DES DONNEES Organisation qui crée l’enregistrement de ces données ';

------------ Relationships and Value Tables ----------- ;

CREATE TABLE tdh_vl.data_media_kind () INHERITS (tdh_vl.value_list_base);
ALTER TABLE tdh_vl.data_media_kind ADD CONSTRAINT pkey_tdh_vl_data_media_kind_code PRIMARY KEY (code);
 INSERT INTO tdh_vl.data_media_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3784,3784,'other','andere','autre', 'altro', 'rrr_altul', '', '', '', '', '', '', '', '', '', '', 'other', 'andere', 'autre', '', '', 'true');
 INSERT INTO tdh_vl.data_media_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3785,3785,'CD','CD','CD', 'CD', 'CD', '', '', '', '', '', '', '', '', '', '', 'CD', 'CD', 'CD', '', 'CD', 'true');
 INSERT INTO tdh_vl.data_media_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3786,3786,'floppy_disc','Diskette','disquette', 'dischetto', '', '', '', '', '', '', '', '', '', '', '', 'floppy_disc', 'Diskette', 'disquette', '', '', 'true');
 INSERT INTO tdh_vl.data_media_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3787,3787,'dvd','DVD','DVD', 'DVD', 'DVD', '', '', '', '', '', '', '', '', '', '', 'dvd', 'DVD', 'DVD', '', '', 'true');
 INSERT INTO tdh_vl.data_media_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3788,3788,'harddisc','Festplatte','disque_dur', 'disco_fisso', '', '', '', '', '', '', '', '', '', '', '', 'harddisc', 'Festplatte', 'disque dur', '', '', 'true');
 INSERT INTO tdh_vl.data_media_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3789,3789,'server','Server','serveur', 'server', 'server', '', '', '', '', '', 'Local server (as opposed to Webserver)', 'Lokaler Server (im Gegensatz zu Webserver)', 'Serveur local (par opposition à serveur web)', 'Server locale (rispetto all server web)', 'Server local (spre deosebire de server web)', 'server', 'Server', '', '', '', 'true');
 INSERT INTO tdh_vl.data_media_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3790,3790,'videotape','Videoband','bande_video', 'nastro_video', 'rrr_Videoband', '', '', '', '', '', '', '', '', '', '', 'videotape', 'Videoband', 'bande vidéo', '', '', 'true');
 INSERT INTO tdh_vl.data_media_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9318,9318,'webserver','Webserver','serveur_web', 'server_web', 'server_web', '', '', '', '', '', 'Web server with URI (https://de.wikipedia.org/wiki/Uniform_Resource_Identifier)', 'Webserver mit URI (https://de.wikipedia.org/wiki/Uniform_Resource_Identifier)', 'Serveur web avec URI (https://de.wikipedia.org/wiki/Uniform_Resource_Identifier)', 'Server web con URI (https://de.wikipedia.org/wiki/Uniform_Resource_Identifier)', 'Server web cu URI (https://de.wikipedia.org/wiki/Uniform_Resource_Identifier)', 'webserver', 'Webserver', 'serveur web', '', '', 'true');
 ALTER TABLE tdh_od.data_media ADD CONSTRAINT fkey_vl_data_media_kind FOREIGN KEY (kind)
 REFERENCES tdh_vl.data_media_kind (code) MATCH SIMPLE
 ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE tdh_od.file ADD COLUMN fk_data_media varchar(16);
ALTER TABLE tdh_od.file ADD CONSTRAINT rel_file_data_media FOREIGN KEY (fk_data_media) REFERENCES tdh_od.data_media(obj_id) ON UPDATE CASCADE ON DELETE set null DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE tdh_vl.file_classname () INHERITS (tdh_vl.value_list_base);
ALTER TABLE tdh_vl.file_classname ADD CONSTRAINT pkey_tdh_vl_file_classname_code PRIMARY KEY (code);
/* TO be set with TDH classes instead of wastewater classes
/*  INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9044,9044,'drainless_toilet','Abflusslose_Toilette','TOILETTE_SANS_VIDANGE', 'toilette_senza_scarico', 'rrr_Abflusslose_Toilette', '', '', '', '', '', 'drainless toilet', 'Abflusslose Toilette', '', '', '', 'drainless_toilet', 'Abflusslose_Toilette', 'TOILETTE_SANS_VIDANGE', '', 'rrr_Abflusslose_Toilette', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9042,9042,'disposal_without_drain','AbflussloseEntsorgung','EVACUATION_SANS_REJET', 'zzz_AbflussloseEntsorgung', 'rrr_AbflussloseEntsorgung', '', '', '', '', '', '', '', '', '', '', 'disposal_without_drain', 'AbflussloseEntsorgung', 'EVACUATION_SANS_REJET', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3800,3800,'throttle_shut_off_unit','Absperr_Drosselorgan','LIMITEUR_DEBIT', 'zzz_Absperr_Drosselorgan', 'rrr_Absperr_Drosselorgan', '', '', '', '', '', '', '', '', '', '', 'throttle_shut_off_unit', 'Absperr_Drosselorgan', 'limiteur de debit', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3801,3801,'wastewater_structure','Abwasserbauwerk','OUVRAGE_RESEAU_AS', 'manufatto_smaltimento_acque', 'rrr_Abwasserbauwerk', '', '', '', '', '', '', '', '', 'manufatto_smaltimento_acque', '', 'wastewater_structure', 'Abwasserbauwerk', 'OUVRAGE_RESEAU_AS', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3802,3802,'waster_water_treatment','Abwasserbehandlung','TRAITEMENT_EAUX_USEES', 'zzz_Abwasserbehandlung', 'rrr_Abwasserbehandlung', '', '', '', '', '', '', '', '', '', '', 'waster_water_treatment', 'Abwasserbehandlung', 'TRAITEMENT_EAUX_USEES', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3803,3803,'wastewater_node','Abwasserknoten','NOEUD_RESEAU', 'zzz_Abwasserknoten', 'rrr_Abwasserknoten', '', '', '', '', '', '', '', '', '', '', 'wastewater_node', 'Abwasserknoten', 'NOEUD_RESEAU', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3804,3804,'wastewater_networkelement','Abwassernetzelement','ELEMENT_RESEAU_EVACUATION', 'zzz_Abwassernetzelement', 'rrr_Abwassernetzelement', '', '', '', '', '', '', '', '', '', '', 'wastewater_networkelement', 'Abwassernetzelement', 'ELEMENT_RESEAU_EVACUATION', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3805,3805,'waste_water_treatment_plant','Abwasserreinigungsanlage','STATION_EPURATION', 'zzz_Abwasserreinigungsanlage', 'rrr_Abwasserreinigungsanlage', '', '', '', '', '', '', '', '', '', '', 'waste_water_treatment_plant', 'Abwasserreinigungsanlage', 'STATION_EPURATION', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3806,3806,'waste_water_association','Abwasserverband','ASSOCIATION_EPURATION_EAU', 'consorzio_depurazione', 'rrr_Abwasserverband', '', '', '', '', '', '', '', '', '', '', 'waste_water_association', 'Abwasserverband', 'ASSOCIATION_EPURATION_EAU', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3807,3807,'administrative_office','Amt','OFFICE', 'zzz_Amt', 'rrr_Amt', '', '', '', '', '', '', '', '', '', '', 'administrative_office', 'Amt', 'OFFICE', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3808,3808,'connection_object','Anschlussobjekt','OBJET_RACCORDE', 'zzz_Anschlussobjekt', 'rrr_Anschlussobjekt', '', '', '', '', '', '', '', '', '', '', 'connection_object', 'Anschlussobjekt', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3809,3809,'wwtp_structure','ARABauwerk','OUVRAGES_STEP', 'manufatto_IDA', 'rrr_ARABauwerk', '', '', '', '', '', '', '', '', '', '', 'wwtp_structure', 'ARABauwerk', 'OUVRAGES_STEP', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3810,3810,'wwtp_energy_use','ARAEnergienutzung','CONSOMMATION_ENERGIE_STEP', 'zzz_ARAEnergienutzung', 'rrr_ARAEnergienutzung', '', '', '', '', '', '', '', '', '', '', 'wwtp_energy_use', 'ARAEnergienutzung', 'CONSOMMATION_ENERGIE_STEP', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3811,3811,'bathing_area','Badestelle','LIEU_BAIGNADE', 'zzz_Badestelle', 'rrr_Badestelle', '', '', '', '', '', '', '', '', '', '', 'bathing_area', 'Badestelle', 'lieu baignade', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3812,3812,'benching','Bankett','BANQUETTE', 'zzz_Bankett', 'rrr_Bankett', '', '', '', '', '', '', '', '', '', '', 'benching', 'Bankett', 'BANQUETTE', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3813,3813,'structure_part','BauwerksTeil','ELEMENT_OUVRAGE', 'zzz_BauwerksTeil', 'rrr_BauwerksTeil', '', '', '', '', '', '', '', '', '', '', 'structure_part', 'BauwerksTeil', 'élement ouvrage', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9038,9038,'tank_emptying','Beckenentleerung','VIDANGE_DE_BASSINS', 'vuotamento_bacino', 'rrr_Beckenentleerung', '', '', '', '', '', '', '', '', '', '', 'tank_emptying', 'Beckenentleerung', 'VIDANGE_DE_BASSINS', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9039,9039,'tank_cleaning','Beckenreinigung','NETTOYAGE_DE_BASSINS', 'pulizia_bacino', 'rrr_Beckenreinigung', '', '', '', '', '', '', '', '', '', '', 'tank_cleaning', 'Beckenreinigung', 'NETTOYAGE_DE_BASSINS', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9027,9027,'bio_ecol_assessment','Biol_oekol_Gesamtbeurteilung','EVALUATION_GENERALE_ECO_BIOL', 'valutazione_biol_ecol_globale', 'rrr_Biol_oekol_Gesamtbeurteilung', '', '', '', '', '', '', '', '', '', '', 'bio_ecol_assessment', 'Biol_oekol_Gesamtbeurteilung', 'EVALUATION_GENERALE_ECO_BIOL', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3814,3814,'well','Brunnen','FONTAINE', 'zzz_Brunnen', 'rrr_Brunnen', '', '', '', '', '', '', '', '', '', '', 'well', 'Brunnen', 'FONTAINE', '', '', 'true'); */
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3815,3815,'file','Datei','FICHIER', 'file', 'rrr_Datei', '', '', '', '', '', '', '', '', '', '', 'file', 'Datei', 'fichier', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3816,3816,'data_media','Datentraeger','SUPPORT_DONNEES', 'supporto_dati', 'rrr_Datentraeger', '', '', '', '', '', '', '', '', '', '', 'data_media', 'Datentraeger', '', '', '', 'true');
/*  INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3817,3817,'cover','Deckel','COUVERCLE', 'zzz_Deckel', 'rrr_Deckel', '', '', '', '', '', '', '', '', '', '', 'cover', 'Deckel', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3818,3818,'passage','Durchlass','PASSAGE_SOUS_TUYAU', 'zzz_Durchlass', 'rrr_Durchlass', '', '', '', '', '', '', '', '', '', '', 'passage', 'Durchlass', 'PASSAGE_SOUS_TUYAU', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (5083,5083,'discharge_point','Einleitstelle','EXUTOIRE', 'punto_immissione', 'deversor', '', '', '', '', '', '', '', '', '', '', 'discharge_point', 'Einleitstelle', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3819,3819,'access_aid','Einstiegshilfe','DISPOSITIF_ACCES', 'zzz_Einstiegshilfe', 'rrr_Einstiegshilfe', '', '', '', '', '', '', '', '', '', '', 'access_aid', 'Einstiegshilfe', 'dispositif access', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3820,3820,'individual_surface','Einzelflaeche','SURFACE_INDIVIDUELLE', 'zzz_Einzelflaeche', 'rrr_Einzelflaeche', '', '', '', '', '', '', '', '', '', '', 'individual_surface', 'Einzelflaeche', 'SURFACE_INDIVIDUELLE', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3821,3821,'catchment_area','Einzugsgebiet','BASSIN_VERSANT', 'area_tributaria', 'rrr_Einzugsgebiet', '', '', '', '', '', '', '', '', '', '', 'catchment_area', 'Einzugsgebiet', 'BASSIN_VERSANT', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3822,3822,'electric_equipment','ElektrischeEinrichtung','EQUIPEMENT_ELECTRIQUE', 'zzz_ElektrischeEinrichtung', 'rrr_ElektrischeEinrichtung', '', '', '', '', '', '', '', '', '', '', 'electric_equipment', 'ElektrischeEinrichtung', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3823,3823,'electromechanical_equipment','ElektromechanischeAusruestung','EQUIPEMENT_ELECTROMECA', 'zzz_ElektromechanischeAusruestung', 'rrr_ElektromechanischeAusruestung', '', '', '', '', '', '', '', '', '', '', 'electromechanical_equipment', 'ElektromechanischeAusruestung', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9028,9028,'disposal','Entsorgung','EVACUATION', 'zzz_Entsorgung', 'rrr_Entsorgung', '', '', '', '', '', '', '', '', '', '', 'disposal', 'Entsorgung', 'EVACUATION', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9043,9043,'disposal_with_drain','EntsorgungMitAbfluss','EVACUATION_AVEC_REJET', 'zzz_EntsorgungMitAbfluss', 'rrr_EntsorgungMitAbfluss', '', '', '', '', '', '', '', '', '', '', 'disposal_with_drain', 'EntsorgungMitAbfluss', 'EVACUATION_AVEC_REJET', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3824,3824,'drainage_system','Entwaesserungssystem','systeme_evacuation_eaux', 'zzz_Entwaesserungssystem', 'rrr_Entwaesserungssystem', '', '', '', '', '', '', '', '', '', '', 'drainage_system', 'Entwaesserungssystem', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3825,3825,'maintenance_event','Erhaltungsereignis','EVENEMENT_MAINTENANCE', 'evento_di_mantenimento', 'rrr_Erhaltungsereignis', '', '', '', '', '', '', '', '', '', '', 'maintenance_event', 'Erhaltungsereignis', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9029,9029,'solids_retention','Feststoffrueckhalt','RETENUE_DE_MATIERES_SOLIDES', 'ritenzione_solidi', 'rrr_Feststoffrueckhalt', '', '', '', '', '', '', '', '', '', '', 'solids_retention', 'Feststoffrueckhalt', 'RETENUE_DE_MATIERES_SOLIDES', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3826,3826,'fish_pass','Fischpass','ECHELLE_POISSONS', 'zzz_Fischpass', 'rrr_Fischpass', '', '', '', '', '', '', '', '', '', '', 'fish_pass', 'Fischpass', 'échelle poissons', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3827,3827,'river','Fliessgewaesser','COURS_EAU', 'zzz_Fliessgewaesser', 'rrr_Fliessgewaesser', '', '', '', '', '', '', '', '', '', '', 'river', 'Fliessgewaesser', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3828,3828,'pump','FoerderAggregat','INSTALLATION_REFOULEMENT', 'pompaggio', 'rrr_FoerderAggregat', '', '', '', '', '', '', '', 'installation de refoulement', '', '', 'pump', 'FoerderAggregat', 'INSTALLATION_REFOULEMENT', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3829,3829,'ford','Furt','PASSAGE_A_GUE', 'zzz_Furt', 'rrr_Furt', '', '', '', '', '', '', '', '', '', '', 'ford', 'Furt', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3830,3830,'building','Gebaeude','BATIMENT', 'zzz_Gebaeude', 'rrr_Gebaeude', '', '', '', '', '', '', '', '', '', '', 'building', 'Gebaeude', 'BATIMENT', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9030,9030,'building_group','Gebaeudegruppe','BATIMENTS', 'zzz_Gebaeudegruppe', 'rrr_Gebaeudegruppe', '', '', '', '', '', '', '', '', '', '', 'building_group', 'Gebaeudegruppe', 'BATIMENTS', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9031,9031,'building_group_baugwr','Gebaeudegruppe_BAUGWR','BATIMENTS_BAUREGBL', 'zzz_Gebaeudegruppe_BAUGWR', 'rrr_Gebaeudegruppe_BAUGWR', '', '', '', '', '', '', '', '', '', '', 'building_group_baugwr', 'Gebaeudegruppe_BAUGWR', 'BATIMENTS_BAUREGBL', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3831,3831,'hazard_source','Gefahrenquelle','SOURCE_DANGER', 'zzz_Gefahrenquelle', 'rrr_hart', '', '', '', '', '', '', '', '', '', '', 'hazard_source', 'Gefahrenquelle', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3832,3832,'municipality','Gemeinde','COMMUNE', 'comune', 'municipiul', '', '', '', '', '', '', '', '', '', '', 'municipality', 'Gemeinde', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9032,9032,'cooperative','Genossenschaft_Korporation','COOPERATIVE', 'cooperativa_corporazione', 'rrr_Genossenschaft_Korporation', '', '', '', '', '', '', '', '', '', '', 'cooperative', 'Genossenschaft_Korporation', 'COOPERATIVE', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9041,9041,'catchment_area_totals','Gesamteinzugsgebiet','BASSIN_VERSANT_COMPLET', 'area_tributaria_totale', 'rrr_Gesamteinzugsgebiet', '', '', '', '', '', '', '', '', '', '', 'catchment_area_totals', 'Gesamteinzugsgebiet', 'BASSIN_VERSANT_COMPLET', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3833,3833,'blocking_debris','Geschiebesperre','BARRAGE_ALLUVIONS', 'zzz_Geschiebesperre', 'rrr_Geschiebesperre', '', '', '', '', '', '', '', '', '', '', 'blocking_debris', 'Geschiebesperre', 'BARRAGE_ALLUVIONS', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3834,3834,'water_course_segment','Gewaesserabschnitt','TRONCON_COURS_EAU', 'zzz_Gewaesserabschnitt', 'rrr_Gewaesserabschnitt', '', '', '', '', '', '', '', '', '', '', 'water_course_segment', 'Gewaesserabschnitt', 'TRONCON_COURS_EAU', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3835,3835,'chute','GewaesserAbsturz','SEUIL', 'zzz_GewaesserAbsturz', 'rrr_GewaesserAbsturz', '', '', '', '', '', '', '', '', '', '', 'chute', 'GewaesserAbsturz', 'SEUIL', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3836,3836,'water_body_protection_sector','Gewaesserschutzbereich','SECTEUR_PROTECTION_EAUX', 'zzz_Gewaesserschutzbereich', 'rrr_Gewaesserschutzbereich', '', '', '', '', '', '', '', '', '', '', 'water_body_protection_sector', 'Gewaesserschutzbereich', 'SECTEUR_PROTECTION_EAUX', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3837,3837,'sector_water_body','Gewaessersektor','SECTEUR_EAUX_SUP', 'zzz_Gewaessersektor', 'rrr_Gewaessersektor', '', '', '', '', '', '', '', '', '', '', 'sector_water_body', 'Gewaessersektor', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3838,3838,'river_bed','Gewaessersohle','FOND_COURS_EAU', 'zzz_Gewaessersohle', 'rrr_Gewaessersohle', '', '', '', '', '', '', '', '', '', '', 'river_bed', 'Gewaessersohle', 'fond cours d''eau', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3839,3839,'water_control_structure','Gewaesserverbauung','AMENAGEMENT_COURS_EAU', 'zzz_Gewaesserverbauung', 'rrr_Gewaesserverbauung', '', '', '', '', '', '', '', '', '', '', 'water_control_structure', 'Gewaesserverbauung', 'AMENAGEMENT_COURS_EAU', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3840,3840,'dam','GewaesserWehr','OUVRAGE_RETENUE', 'zzz_GewaesserWehr', 'rrr_GewaesserWehr', '', '', '', '', '', '', '', '', '', '', 'dam', 'GewaesserWehr', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3841,3841,'aquifer','Grundwasserleiter','AQUIFERE', 'acquifero', 'rrr_Grundwasserleiter', '', '', '', '', '', '', '', '', '', '', 'aquifer', 'Grundwasserleiter', 'AQUIFERE', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3842,3842,'ground_water_protection_perimeter','Grundwasserschutzareal','PERIMETRE_PROT_EAUX_SOUT', 'zzz_Grundwasserschutzareal', 'rrr_Grundwasserschutzareal', '', '', '', '', '', '', '', '', '', '', 'ground_water_protection_perimeter', 'Grundwasserschutzareal', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3843,3843,'groundwater_protection_zone','Grundwasserschutzzone','ZONE_PROT_EAUX_SOUT', 'zzz_Grundwasserschutzzone', 'rrr_Grundwasserschutzzone', '', '', '', '', '', '', '', '', '', '', 'groundwater_protection_zone', 'Grundwasserschutzzone', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3844,3844,'reach','Haltung','TRONCON', 'tratta', 'rrr_Haltung', '', '', '', '', '', '', '', '', '', '', 'reach', 'Haltung', 'TRONCON', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3845,3845,'reach_point','Haltungspunkt','POINT_TRONCON', 'punto_tratta', 'rrr_Haltungspunkt', '', '', '', '', '', '', '', '', '', '', 'reach_point', 'Haltungspunkt', 'POINT_TRONCON', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3846,3846,'hq_relation','HQ_Relation','RELATION_HQ', 'zzz_HQ_Relation', 'rrr_HQ_Relation', '', '', '', '', '', '', '', '', '', '', 'hq_relation', 'HQ_Relation', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3847,3847,'hydr_geometry','Hydr_Geometrie','GEOMETRIE_HYDR', 'zzz_Hydr_Geometrie', 'rrr_Hydr_Geometrie', '', '', '', '', '', '', '', '', '', '', 'hydr_geometry', 'Hydr_Geometrie', 'Géométrie hydraulique', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3848,3848,'hydr_geom_relation','Hydr_GeomRelation','RELATION_GEOM_HYDR', 'zzz_Hydr_GeomRelation', 'rrr_Hydr_GeomRelation', '', '', '', '', '', '', '', '', '', '', 'hydr_geom_relation', 'Hydr_GeomRelation', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9033,9033,'hydraulic_char_data','Hydr_Kennwerte','PARAMETRES_HYDR', 'zzz_Hydr_Kennwerte', 'rrr_Hydr_Kennwerte', '', '', '', '', '', '', '', '', '', '', 'hydraulic_char_data', 'Hydr_Kennwerte', 'PARAMETRES_HYDR', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3849,3849,'channel','Kanal','CANALISATION', 'zzz_Kanal', 'rrr_Kanal', '', '', '', '', '', '', '', '', '', '', 'channel', 'Kanal', 'CANALISATION', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3850,3850,'damage_channel','Kanalschaden','DOMMAGE_AUX_CANALISATIONS', 'zzz_Kanalschaden', 'rrr_Kanalschaden', '', '', '', '', '', '', '', '', '', '', 'damage_channel', 'Kanalschaden', 'dommage aux canalisation', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3851,3851,'canton','Kanton','CANTON', 'zzz_Kanton', '', '', '', '', '', '', '', '', '', '', '', 'canton', 'Kanton', 'CANTON', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9034,9034,'small_treatment_plant','KLARA','PETITE_STEP', 'zzz_KLARA', 'rrr_KLARA', '', '', '', '', '', '', '', '', '', '', 'small_treatment_plant', 'KLARA', 'PETITE_STEP', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9035,9035,'farm','Landwirtschaftsbetrieb','EXPLOITATION_AGRICOLE', 'zzz_Landwirtschaftsbetrieb', 'rrr_Landwirtschaftsbetrieb', '', '', '', '', '', '', '', '', '', '', 'farm', 'Landwirtschaftsbetrieb', 'EXPLOITATION_AGRICOLE', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3852,3852,'leapingweir','Leapingwehr','LEAPING_WEIR', 'leaping_weir', 'rrr_Leapingwehr', '', '', '', '', '', '', '', '', '', '', 'leapingweir', 'Leapingwehr', 'leapingweir', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9036,9036,'measure','Massnahme','MESURE', 'intervento', 'rrr_Massnahme', '', '', '', '', '', '', '', '', '', '', 'measure', 'Massnahme', 'MESURE', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3853,3853,'mechanical_pretreatment','MechanischeVorreinigung','PRETRAITEMENT_MECANIQUE', 'zzz_MechanischeVorreinigung', 'rrr_MechanischeVorreinigung', '', '', '', '', '', '', '', '', '', '', 'mechanical_pretreatment', 'MechanischeVorreinigung', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3854,3854,'measurement_device','Messgeraet','APPAREIL_MESURE', 'apparecchio_misura', 'rrr_Messgeraet', '', '', '', '', '', '', '', '', '', '', 'measurement_device', 'Messgeraet', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3855,3855,'measurement_series','Messreihe','SERIE_MESURES', 'zzz_Messreihe', 'rrr_Messreihe', '', '', '', '', '', '', '', '', '', '', 'measurement_series', 'Messreihe', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3856,3856,'measurement_result','Messresultat','RESULTAT_MESURE', 'zzz_Messresultat', 'rrr_Messresultat', '', '', '', '', '', '', '', '', '', '', 'measurement_result', 'Messresultat', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3857,3857,'measuring_point','Messstelle','STATION_MESURE', 'stazione_misura', 'rrr_Messstelle', '', '', '', '', '', '', '', '', '', '', 'measuring_point', 'Messstelle', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3858,3858,'standard_manhole','Normschacht','CHAMBRE_STANDARD', 'zzz_Normschacht', 'rrr_Normschacht', '', '', '', '', '', '', '', '', '', '', 'standard_manhole', 'Normschacht', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3859,3859,'damage_manhole','Normschachtschaden','DOMMAGE_CHAMBRE_STANDARD', 'zzz_Normschachtschaden', 'rrr_Normschachtschaden', '', '', '', '', '', '', '', '', '', '', 'damage_manhole', 'Normschachtschaden', 'dommage chambre standard', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3861,3861,'surface_runoff_parameters','Oberflaechenabflussparameter','PARAM_ECOULEMENT_SUP', 'zzz_Oberflaechenabflussparameter', 'rrr_Oberflaechenabflussparameter', '', '', '', '', '', '', '', '', '', '', 'surface_runoff_parameters', 'Oberflaechenabflussparameter', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3862,3862,'surface_water_bodies','Oberflaechengewaesser','EAUX_SUPERFICIELLES', 'zzz_Oberflaechengewaesser', 'rrr_Oberflaechengewaesser', '', '', '', '', '', '', '', '', '', '', 'surface_water_bodies', 'Oberflaechengewaesser', 'eaux superficielles', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3863,3863,'organisation','Organisation','ORGANISATION', 'organizzazione', 'rrr_Organisation', '', '', '', '', '', '', '', '', '', '', 'organisation', 'Organisation', 'ORGANISATION', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3864,3864,'planning_zone','Planungszone','ZONE_RESERVEE', 'zzz_Planungszone', 'rrr_Planungszone', '', '', '', '', '', '', '', '', '', '', 'planning_zone', 'Planungszone', 'ZONE_RESERVEE', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3865,3865,'private','Privat','PRIVE', 'privato', 'privata', '', '', '', '', '', '', '', '', '', '', 'private', 'Privat', 'PRIVE', '', 'privata', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3866,3866,'cleaning_device','Reinigungseinrichtung','DISPOSITIF_NETTOYAGE', 'zzz_Reinigungseinrichtung', 'rrr_Reinigungseinrichtung', '', '', '', '', '', '', '', '', '', '', 'cleaning_device', 'Reinigungseinrichtung', 'dispositif nettoyage', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3867,3867,'reservoir','Reservoir','RESERVOIR', 'zzz_Reservoir', 'rrr_Reservoir', '', '', '', '', '', '', '', '', '', '', 'reservoir', 'Reservoir', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3868,3868,'retention_body','Retentionskoerper','VOLUME_RETENTION', 'zzz_Retentionskoerper', 'rrr_Retentionskoerper', '', '', '', '', '', '', '', '', '', '', 'retention_body', 'Retentionskoerper', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3869,3869,'pipe_profile','Rohrprofil','PROFIL_TUYAU', 'profilo_del_tubo', 'rrr_Rohrprofil', '', '', '', '', '', '', '', '', '', '', 'pipe_profile', 'Rohrprofil', 'PROFIL_TUYAU', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3870,3870,'profile_geometry','Rohrprofil_Geometrie','PROFIL_TUYAU_GEOM', 'zzz_Rohrprofil_Geometrie', '', '', '', '', '', '', '', '', '', '', '', 'profile_geometry', 'Rohrprofil_Geometrie', 'PROFIL_TUYAU_GEOM', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9040,9040,'backflow_prevention','Rueckstausicherung','PROTECTION_REFOULEMENT', 'dispositivo_anti_rigurgito', 'rrr_Rueckstausicherung', '', '', '', '', '', '', '', '', '', '', 'backflow_prevention', 'Rueckstausicherung', 'PROTECTION_REFOULEMENT', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3871,3871,'damage','Schaden','DOMMAGE', 'zzz_Schaden', 'rrr_Schaden', '', '', '', '', '', '', '', '', '', '', 'damage', 'Schaden', 'dommage', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3872,3872,'sludge_treatment','Schlammbehandlung','TRAITEMENT_BOUES', 'zzz_Schlammbehandlung', 'rrr_Schlammbehandlung', '', '', '', '', '', '', '', '', '', '', 'sludge_treatment', 'Schlammbehandlung', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3873,3873,'lock','Schleuse','ECLUSE', 'zzz_Schleuse', 'rrr_Schleuse', '', '', '', '', '', '', '', '', '', '', 'lock', 'Schleuse', 'éclues', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3874,3874,'lake','See','LAC', 'lago', 'rrr_See', '', '', '', '', '', '', '', '', '', '', 'lake', 'See', 'lac', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3875,3875,'rock_ramp','Sohlrampe','RAMPE', 'zzz_Sohlrampe', 'rrr_Sohlrampe', '', '', '', '', '', '', '', '', '', '', 'rock_ramp', 'Sohlrampe', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3876,3876,'special_structure','Spezialbauwerk','OUVRAGE_SPECIAL', 'zzz_Spezialbauwerk', 'rrr_Spezialbauwerk', '', '', '', '', '', '', '', '', '', '', 'special_structure', 'Spezialbauwerk', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9026,9026,'flushing_nozzle','Spuelstutzen','TETE_DE_RINCAGE', 'zzz_Ugello_di_lavaggio', 'rrr_Spuelstutzen', '', '', '', '', '', '', '', '', '', '', 'flushing_nozzle', 'Spuelstutzen', 'TETE_DE_RINCAGE', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9037,9037,'log_card','Stammkarte','FICHE_TECHNIQUE', 'scheda_tipo', 'rrr_Stammkarte', '', '', '', '', '', '', '', '', '', '', 'log_card', 'Stammkarte', 'FICHE_TECHNIQUE', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3877,3877,'control_center','Steuerungszentrale','CENTRALE_COMMANDE', 'zzz_Steuerungszentrale', 'rrr_Steuerungszentrale', '', '', '', '', '', '', '', '', '', '', 'control_center', 'Steuerungszentrale', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3878,3878,'substance','Stoff','SUBSTANCE', 'zzz_Stoff', 'rrr_Stoff', '', '', '', '', '', '', '', '', '', '', 'substance', 'Stoff', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3879,3879,'prank_weir','Streichwehr','DEVERSOIR_LATERAL', 'stramazzo_laterale', 'rrr_Streichwehr', '', '', '', '', '', '', '', '', '', '', 'prank_weir', 'Streichwehr', 'DEVERSOIR_LATERAL', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3880,3880,'dryweather_downspout','Trockenwetterfallrohr','TUYAU_CHUTE', 'zzz_Trockenwetterfallrohr', 'rrr_Trockenwetterfallrohr', '', '', '', '', '', '', '', '', '', '', 'dryweather_downspout', 'Trockenwetterfallrohr', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3881,3881,'dryweather_flume','Trockenwetterrinne','CUNETTE_DEBIT_TEMPS_SEC', 'zzz_Trockenwetterrinne', 'rrr_Trockenwetterrinne', '', '', '', '', '', '', '', '', '', '', 'dryweather_flume', 'Trockenwetterrinne', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3882,3882,'overflow','Ueberlauf','DEVERSOIR', 'zzz_Ueberlauf', 'rrr_Ueberlauf', '', '', '', '', '', '', '', '', '', '', 'overflow', 'Ueberlauf', 'DEVERSOIR', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3883,3883,'overflow_characteristic','Ueberlaufcharakteristik','CARACTERISTIQUES_DEVERSOIR', 'zzz_Ueberlaufcharakteristik', 'rrr_Ueberlaufcharakteristik', '', '', '', '', '', '', '', '', '', '', 'overflow_characteristic', 'Ueberlaufcharakteristik', 'CARACTERISTIQUES_DEVERSOIR', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3884,3884,'shore','Ufer','RIVE', 'zzz_Ufer', 'rrr_Ufer', '', '', '', '', '', '', '', '', '', '', 'shore', 'Ufer', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3885,3885,'accident','Unfall','ACCIDENT', 'zzz_Unfall', 'rrr_Unfall', '', '', '', '', '', '', '', '', '', '', 'accident', 'Unfall', 'ACCIDENT', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3886,3886,'examination','Untersuchung','EXAMEN', 'zzz_Untersuchung', 'rrr_Untersuchung', '', '', '', '', '', '', '', '', '', '', 'examination', 'Untersuchung', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3887,3887,'infiltration_installation','Versickerungsanlage','INSTALLATION_INFILTRATION', 'impianto_infiltrazione', 'rrr_Versickerungsanlage', '', '', '', '', '', '', '', '', '', '', 'infiltration_installation', 'Versickerungsanlage', 'Installation d''infiltration', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3888,3888,'infiltration_zone','Versickerungsbereich','ZONE_INFILTRATION', 'zzz_Versickerungsbereich', 'rrr_Versickerungsbereich', '', '', '', '', '', '', '', '', '', '', 'infiltration_zone', 'Versickerungsbereich', '', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3890,3890,'water_catchment','Wasserfassung','CAPTAGE', 'zzz_Wasserfassung', 'rrr_Wasserfassung', '', '', '', '', '', '', '', '', '', '', 'water_catchment', 'Wasserfassung', 'CAPTAGE', '', '', 'true');
 INSERT INTO tdh_vl.file_classname (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3891,3891,'zone','Zone','ZONE', 'zzz_Zone', 'rrr_Zone', '', '', '', '', '', '', '', '', '', '', 'zone', 'Zone', 'ZONE', '', '', 'true'); */
 ALTER TABLE tdh_od.file ADD CONSTRAINT fkey_vl_file_classname FOREIGN KEY (classname)
 REFERENCES tdh_vl.file_classname (code) MATCH SIMPLE
 ON UPDATE RESTRICT ON DELETE RESTRICT;
CREATE TABLE tdh_vl.file_kind () INHERITS (tdh_vl.value_list_base);
ALTER TABLE tdh_vl.file_kind ADD CONSTRAINT pkey_tdh_vl_file_kind_code PRIMARY KEY (code);
 INSERT INTO tdh_vl.file_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3770,3770,'other','andere','autre', 'altro', 'rrr_altul', '', '', '', '', '', '', '', '', '', '', 'other', 'andere', 'autre', '', '', 'true');
 INSERT INTO tdh_vl.file_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9146,9146,'digital_video','digitales_Video','video_numerique', 'video_digitale', 'rrr_digitales_Video', '', '', '', '', '', '', '', '', '', '', 'digital_video', 'digitales_Video', 'vidéo numérique', '', '', 'true');
 INSERT INTO tdh_vl.file_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3772,3772,'photo','Foto','photo', 'foto', 'foto', '', '', '', '', '', '', '', '', '', '', 'photo', 'Foto', 'photo', '', '', 'true');
 INSERT INTO tdh_vl.file_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3773,3773,'panoramo_film','Panoramofilm','film_panoramique', 'film_panoramico', 'rrr_Panoramofilm', '', '', '', '', '', '', '', '', '', '', 'panoramo_film', 'Panoramofilm', 'film panoramique', '', '', 'true');
 INSERT INTO tdh_vl.file_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (9147,9147,'scan','Scan','scan', 'scan', 'scanare', '', '', '', '', '', '', '', '', '', '', 'scan', 'Scan', 'scan', '', '', 'true');
 INSERT INTO tdh_vl.file_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (8812,8812,'sketch','Skizze','croquis', 'schizzo', 'schita', '', '', '', '', '', '', '', '', '', '', 'sketch', 'Skizze', 'croquis', '', 'Schi?a', 'true');
 INSERT INTO tdh_vl.file_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3774,3774,'textfile','Textdatei','fichier_texte', 'file_di_testo', 'rrr_Textdatei', '', '', '', '', '', '', '', '', '', '', 'textfile', 'Textdatei', 'fichier texte', '', '', 'true');
 INSERT INTO tdh_vl.file_kind (code, vsacode, value_en, value_de, value_fr, value_it, value_ro, abbr_en, abbr_de, abbr_fr, abbr_it, abbr_ro, description_en, description_de, description_fr, description_it, description_ro, display_en, display_de, display_fr, display_it, display_ro, active) VALUES (3775,3775,'video','Video','video', 'video', 'rrr_video', '', '', '', '', '', '', '', '', '', '', 'video', 'Video', 'vidéo', '', '', 'true');
 ALTER TABLE tdh_od.file ADD CONSTRAINT fkey_vl_file_kind FOREIGN KEY (kind)
 REFERENCES tdh_vl.file_kind (code) MATCH SIMPLE
 ON UPDATE RESTRICT ON DELETE RESTRICT;
--------- Relations to class organisation for dataowner and provider (new 3.11.2014);
-------- Relations to class organisation for dataowner and provider;

ALTER TABLE tdh_od.data_media ADD CONSTRAINT rel_od_data_media_fk_dataowner FOREIGN KEY (fk_dataowner) REFERENCES tdh_od.organisation(obj_id);
ALTER TABLE tdh_od.data_media ADD CONSTRAINT rel_od_data_media_fk_dataprovider FOREIGN KEY (fk_provider) REFERENCES tdh_od.organisation(obj_id);
ALTER TABLE tdh_od.file ADD CONSTRAINT rel_od_file_fk_dataowner FOREIGN KEY (fk_dataowner) REFERENCES tdh_od.organisation(obj_id);
ALTER TABLE tdh_od.file ADD CONSTRAINT rel_od_file_fk_dataprovider FOREIGN KEY (fk_provider) REFERENCES tdh_od.organisation(obj_id);

------ Indexes on identifiers

 CREATE UNIQUE INDEX in_od_data_media_identifier ON tdh_od.data_media USING btree (identifier ASC NULLS LAST, fk_dataowner ASC NULLS LAST);
 CREATE UNIQUE INDEX in_od_file_identifier ON tdh_od.file USING btree (identifier ASC NULLS LAST, fk_dataowner ASC NULLS LAST);

 COMMIT;
