 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3754,3764,3819,'file','classname','structure','structure',NULL,'Bauwerk',NULL,'Ouvrage',NULL,'zzz_Bauwerk',NULL,'zzz_Bauwerk',NULL,NULL,NULL,NULL,NULL,NULL);
/* TODO : Add full dictionnary of tdh classnames
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3754,3764,3885,'file','classname','accident','accident',NULL,'Unfall',NULL,'ACCIDENT',NULL,'zzz_Unfall',NULL,'rrr_Unfall',NULL,NULL,NULL,NULL,NULL,NULL); */



 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3754,3769,9146,'file','kind','digital_video','digital_video',NULL,'digitales_Video',NULL,'video_numerique',NULL,'video_digitale',NULL,'rrr_digitales_Video',NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3754,3769,3770,'file','kind','other','other',NULL,'andere',NULL,'autre',NULL,'altro',NULL,'rrr_altul',NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3754,3769,3773,'file','kind','panoramo_film','panoramo_film',NULL,'Panoramofilm',NULL,'film_panoramique',NULL,'film_panoramico',NULL,'rrr_Panoramofilm',NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3754,3769,3772,'file','kind','photo','photo',NULL,'Foto',NULL,'photo',NULL,'foto',NULL,'foto',NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3754,3769,9147,'file','kind','scan','scan',NULL,'Scan',NULL,'scan',NULL,'scan',NULL,'scanare',NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3754,3769,8812,'file','kind','sketch','sketch',NULL,'Skizze',NULL,'croquis',NULL,'schizzo',NULL,'schita',NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3754,3769,3774,'file','kind','textfile','textfile',NULL,'Textdatei',NULL,'fichier_texte',NULL,'file_di_testo',NULL,'rrr_Textdatei',NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3754,3769,3775,'file','kind','video','video',NULL,'Video',NULL,'video',NULL,'video',NULL,'rrr_video',NULL,NULL,NULL,NULL,NULL,NULL);



 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3776,3783,3785,'data_media','kind','CD','CD',NULL,'CD',NULL,'CD',NULL,'CD',NULL,'CD',NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3776,3783,3787,'data_media','kind','dvd','dvd',NULL,'DVD',NULL,'DVD',NULL,'DVD',NULL,'DVD',NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3776,3783,3786,'data_media','kind','floppy_disc','floppy_disc',NULL,'Diskette',NULL,'disquette',NULL,'dischetto',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3776,3783,3788,'data_media','kind','harddisc','harddisc',NULL,'Festplatte',NULL,'disque_dur',NULL,'disco_fisso',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3776,3783,3784,'data_media','kind','other','other',NULL,'andere',NULL,'autre',NULL,'altro',NULL,'rrr_altul',NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3776,3783,3789,'data_media','kind','server','server',NULL,'Server',NULL,'serveur',NULL,'server',NULL,'server',NULL,'Local server (as opposed to Webserver)','Lokaler Server (im Gegensatz zu Webserver)','Serveur local (par opposition à serveur web)','Server locale (rispetto all server web)','Server local (spre deosebire de server web)');
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3776,3783,3790,'data_media','kind','videotape','videotape',NULL,'Videoband',NULL,'bande_video',NULL,'nastro_video',NULL,'rrr_Videoband',NULL,NULL,NULL,NULL,NULL,NULL);
 INSERT INTO tdh_sys.dictionary_od_values (class_id, attribute_id, value_id, table_name, field_name, value_name, value_name_en, shortcut_en, value_name_de, shortcut_de, value_name_fr, shortcut_fr, value_name_it, shortcut_it, value_name_ro, shortcut_ro, value_description_en, value_description_de, value_description_fr, value_description_it, value_description_ro) VALUES (3776,3783,9318,'data_media','kind','webserver','webserver',NULL,'Webserver',NULL,'serveur_web',NULL,'server_web',NULL,'server_web',NULL,'Web server with URI (https://de.wikipedia.org/wiki/Uniform_Resource_Identifier)','Webserver mit URI (https://de.wikipedia.org/wiki/Uniform_Resource_Identifier)','Serveur web avec URI (https://de.wikipedia.org/wiki/Uniform_Resource_Identifier)','Server web con URI (https://de.wikipedia.org/wiki/Uniform_Resource_Identifier)','Server web cu URI (https://de.wikipedia.org/wiki/Uniform_Resource_Identifier)');
