name: 🐘 Datamodel | Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - datamodel/**
      - '.github/workflows/datamodel-test.yml'
  pull_request:
    branches:
      - main
    paths:
      - datamodel/**
      - '.github/workflows/datamodel-test.yml'
  workflow_dispatch:


jobs:
  datamodel-tests:
    name: Run unit tests on datamodel
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v5

      - name: Docker build
        run: |
          docker build \
          --build-arg RUN_TEST=True \
          -f datamodel/.docker/Dockerfile \
          --tag teksi/district_heating:unstable .

      - name: Initialize container
        run: |
          docker run -d -p 5432:5432 --name teksi-district_heating teksi/district_heating:unstable
          until docker exec teksi-district_heating pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          # create the database
          docker exec teksi-district_heating sh -c 'createdb tdh'
          docker exec teksi-district_heating pum -vvv -s pg_tdh -d datamodel install -p SRID 2056 --roles --grant

      - name: Run tests
        run:  docker exec teksi-district_heating pytest datamodel

      - name: Docker logs
        if: failure()
        run: docker logs teksi-district_heating

  extension-db-initalisation-tests:
    name: Run tests to initialize db with an extended datamodel
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v5

      - name: Docker build
        run: |
          docker build \
          --build-arg RUN_TEST=True \
          -f datamodel/.docker/Dockerfile \
          --tag teksi/district_heating:unstable .

      - name: Initialize container
        run: |
          docker run -d -p 5432:5432 --name teksi-district_heating teksi/district_heating:unstable
          until docker exec teksi-district_heating pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          # create the database
          docker exec teksi-district_heating sh -c 'createdb tdh'
          docker exec teksi-district_heating pum -vvv -s pg_tdh -d datamodel install -p SRID 2056 -p modification_ci --roles --grant

      - name: Docker logs
        if: failure()
        run: docker logs teksi-district_heating

  extension-tests:
    name: Run unit tests on extended datamodel
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v5

      - name: Docker build
        run: |
          docker build \
          --build-arg RUN_TEST=True \
          -f datamodel/.docker/Dockerfile \
          --tag teksi/district_heating:unstable .

      - name: Initialize container
        run: |
          docker run -d -p 5432:5432 --name teksi-district_heating teksi/district_heating:unstable
          until docker exec teksi-district_heating pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          # create the database
          docker exec teksi-district_heating sh -c 'createdb tdh'
          docker exec teksi-district_heating pum -vvv -s pg_tdh -d datamodel install -p SRID 2056 -p modification_${{ matrix.extension }} --roles --grant

      - name: Run tests
        run:  docker exec teksi-district_heating pytest datamodel

      - name: Docker logs
        if: failure()
        run: docker logs teksi-district_heating

  static-tests:
    name: Run static tests on datamodel
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5
    - run: ./datamodel/test/static_tests.sh
