name: 🐘 Datamodel | Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - datamodel/**
      - '.github/workflows/datamodel-test.yml'
  pull_request:
    branches:
      - main
    paths:
      - datamodel/**
      - '.github/workflows/datamodel-test.yml'
  workflow_dispatch:


jobs:
  datamodel-tests:
    name: Run unit tests on datamodel
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        psycopg-version: [ 2, 3 ]
      fail-fast: true

    steps:
      - uses: actions/checkout@v5

      - name: Docker build
        run: |
          docker build \
          --build-arg RUN_TEST=True \
          --build-arg PSYCOPG_VERSION=${{ matrix.psycopg-version }} \
          -f datamodel/.docker/Dockerfile \
          --tag teksi/district_heating:unstable .

      - name: Initialize container
        run: |
          docker run -d -p 5432:5432 --name teksi-district_heating teksi/district_heating:unstable
          docker exec teksi-district_heating init_db.sh wait

      - name: Run tests
        run:  docker exec teksi-district_heating pytest datamodel

      - name: Docker logs
        if: failure()
        run: docker logs teksi-district_heating

  static-tests:
    name: Run static tests on datamodel
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5
    - run: ./datamodel/test/static_tests.sh
